# The URL the site will be built for
base_url = "https://of-the-stars.net"
default_language = "en"
generate_feeds = true
title = "Of The Stars"
author = "Stellae"
generate_robots_txt = true
# Whether to build a search index to be used later on by a JavaScript library
# build_search_index = true
theme = "zola-bearblog"
# Whether to automatically compile all Sass files in the sass directory
# compile_sass = true
taxonomies = [
  { name = "categories", feed = true },
  { name = "tags", feed = true },
]

[translations]
no_posts = "No posts yet"
remove_filter = "Remove filter"
filtering_for = "Filtering for"
made_with = "Made with"
table_of_contents = "Table of contents"
language = "language"
site = "site"

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
# highlight_code = true
# highlight_there = "gruvbox-dark"
# github_alerts = true

[extra]
# Put all your custom variables here
date_format = "%Y-%m-%d"

[[extra.main_menu]]
name = "Home"
url = "@/_index.md"

[[extra.main_menu]]
name = "Blog"
url = "@/blog/_index.md"

[[extra.main_menu]]
name = "Feed"
url = "/atom.xml"
