baseURL = "https://of-the-stars.net/"
languageCode = "en-us"
title = "Of The Stars"
weight = 100
author = "Stellae"
copyright = "Copyright Â© 2025, Of The Stars."
# theme = 'PaperMod'
theme = "hugo-wassail"
# Generate a nice robots.txt for SEO
enableRobotsTXT = true

[params]
description = "My personal blog"
title = "Of The Stars"
hideMadeWithLine = true
dateFormat = "2006-01-02"
enablePostNavigator = true

[markup]
[markup.highlight]
style = "friendly"
lineNos = true
lineNumbersInTable = false
codeFences = true
